[package]
name = "xandeum-config-program"
description = "Solana Config program"
documentation = "https://docs.rs/xandeum-config-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
chrono = { workspace = true, features = ["default", "serde"] }
serde = { workspace = true }
serde_derive = { workspace = true }
xandeum-program-runtime = { workspace = true }
xandeum-sdk = { workspace = true }

[dev-dependencies]
xandeum-logger = { workspace = true }

[lib]
crate-type = ["lib"]
name = "xandeum_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
