[package]
name = "xandeum-sbf-rust-simulation"
description = "Solana SBF Program Simulation Differences"
documentation = "https://docs.rs/xandeum-sbf-rust-simulation"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
test-bpf = []

[dependencies]
xandeum-program = { workspace = true }

[dev-dependencies]
xandeum-logger = { workspace = true }
xandeum-program-test = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-validator = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
