[package]
name = "xandeum-bpf-loader-program"
description = "Solana BPF loader"
documentation = "https://docs.rs/xandeum-bpf-loader-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
byteorder = { workspace = true }
libsecp256k1 = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
xandeum-measure = { workspace = true }
xandeum-program-runtime = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-zk-token-sdk = { workspace = true }
xandeum_rbpf = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
memoffset = { workspace = true }

[lib]
crate-type = ["lib"]
name = "xandeum_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
