[package]
name = "xandeum-stake-program"
description = "Solana Stake program"
documentation = "https://docs.rs/xandeum-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
xandeum-config-program = { workspace = true }
xandeum-program-runtime = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-vote-program = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
proptest = { workspace = true }
xandeum-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "xandeum_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
