[package]
name = "xandeum-rpc"
description = "Solana RPC"
documentation = "https://docs.rs/xandeum-rpc"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive = { workspace = true }
jsonrpc-http-server = { workspace = true }
jsonrpc-pubsub = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
soketto = { workspace = true }
xandeum-account-decoder = { workspace = true }
xandeum-client = { workspace = true }
xandeum-entry = { workspace = true }
xandeum-faucet = { workspace = true }
xandeum-gossip = { workspace = true }
xandeum-ledger = { workspace = true }
xandeum-measure = { workspace = true }
xandeum-metrics = { workspace = true }
xandeum-perf = { workspace = true }
xandeum-poh = { workspace = true }
xandeum-rayon-threadlimit = { workspace = true }
xandeum-rpc-client-api = { workspace = true }
xandeum-runtime = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-send-transaction-service = { workspace = true }
xandeum-stake-program = { workspace = true }
xandeum-storage-bigtable = { workspace = true }
xandeum-streamer = { workspace = true }
xandeum-tpu-client = { workspace = true }
xandeum-transaction-status = { workspace = true }
xandeum-version = { workspace = true }
xandeum-vote-program = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
stream-cancel = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec", "compat"] }

[dev-dependencies]
serial_test = { workspace = true }
xandeum-address-lookup-table-program = { workspace = true }
xandeum-net-utils = { workspace = true }
xandeum-stake-program = { workspace = true }
symlink = { workspace = true }

[lib]
crate-type = ["lib"]
name = "xandeum_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
