[package]
name = "xandeum-validator"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/xandeum-validator"
default-run = "xandeum-validator"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = { workspace = true }
console = { workspace = true }
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
fd-lock = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true, features = ["ipc"] }
jsonrpc-derive = { workspace = true }
jsonrpc-ipc-server = { workspace = true }
jsonrpc-server-utils = { workspace = true }
lazy_static = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
xandeum-clap-utils = { workspace = true }
xandeum-cli-config = { workspace = true }
xandeum-core = { workspace = true }
xandeum-download-utils = { workspace = true }
xandeum-entry = { workspace = true }
xandeum-faucet = { workspace = true }
xandeum-genesis-utils = { workspace = true }
xandeum-geyser-plugin-interface = { workspace = true }
xandeum-geyser-plugin-manager = { workspace = true }
xandeum-gossip = { workspace = true }
xandeum-ledger = { workspace = true }
xandeum-logger = { workspace = true }
xandeum-metrics = { workspace = true }
xandeum-net-utils = { workspace = true }
xandeum-perf = { workspace = true }
xandeum-poh = { workspace = true }
xandeum-rpc = { workspace = true }
xandeum-rpc-client = { workspace = true }
xandeum-rpc-client-api = { workspace = true }
xandeum-runtime = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-send-transaction-service = { workspace = true }
xandeum-storage-bigtable = { workspace = true }
xandeum-streamer = { workspace = true }
xandeum-test-validator = { workspace = true }
xandeum-tpu-client = { workspace = true }
xandeum-version = { workspace = true }
xandeum-vote-program = { workspace = true }
symlink = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
xandeum-account-decoder = { workspace = true }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }
signal-hook = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
