[package]
name = "xandeum-loader-v4-program"
description = "Solana Loader v4"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
rand = { workspace = true }
xandeum-measure = { workspace = true }
xandeum-program-runtime = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum_rbpf = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }

[lib]
crate-type = ["lib"]
name = "xandeum_loader_v4_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
