[package]
name = "xandeum-udp-client"
description = "Solana UDP Client"
documentation = "https://docs.rs/xandeum-udp-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
xandeum-connection-cache = { workspace = true }
xandeum-net-utils = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
