[package]
name = "xandeum-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/xandeum-stake-accounts"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
xandeum-clap-utils = { workspace = true }
xandeum-cli-config = { workspace = true }
xandeum-remote-wallet = { workspace = true, features = ["default"] }
xandeum-rpc-client = { workspace = true, features = ["default"] }
xandeum-rpc-client-api = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-stake-program = { workspace = true }
xandeum-version = { workspace = true }

[dev-dependencies]
xandeum-runtime = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
