[package]
name = "xandeum-watchtower"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/xandeum-watchtower"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }
xandeum-clap-utils = { workspace = true }
xandeum-cli-config = { workspace = true }
xandeum-cli-output = { workspace = true }
xandeum-logger = { workspace = true }
xandeum-metrics = { workspace = true }
xandeum-notifier = { workspace = true }
xandeum-rpc-client = { workspace = true }
xandeum-rpc-client-api = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
