[package]
name = "xandeum-tokens"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/xandeum-tokens"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = "2.33.0"
console = { workspace = true }
csv = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
indexmap = { workspace = true }
indicatif = { workspace = true }
pickledb = { workspace = true, features = ["yaml"] }
serde = { workspace = true, features = ["derive"] }
xandeum-account-decoder = { workspace = true }
xandeum-clap-utils = { workspace = true }
xandeum-cli-config = { workspace = true }
xandeum-remote-wallet = { workspace = true, features = ["default"] }
xandeum-rpc-client = { workspace = true, features = ["default"] }
xandeum-rpc-client-api = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-transaction-status = { workspace = true }
xandeum-version = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
xandeum-logger = { workspace = true }
xandeum-streamer = { workspace = true }
xandeum-test-validator = { workspace = true }
