[package]
name = "xandeum-quic-client"
description = "Solana Quic Client"
documentation = "https://docs.rs/xandeum-quic-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-mutex = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
quinn = { workspace = true }
quinn-proto = { workspace = true }
quinn-udp = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true, features = ["dangerous_configuration"] }
xandeum-connection-cache = { workspace = true }
xandeum-measure = { workspace = true }
xandeum-metrics = { workspace = true }
xandeum-net-utils = { workspace = true }
xandeum-rpc-client-api = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
crossbeam-channel = { workspace = true }
xandeum-logger = { workspace = true }
xandeum-perf = { workspace = true }
