[package]
name = "xandeum-perf"
description = "Solana Performance APIs"
documentation = "https://docs.rs/xandeum-perf"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
ahash = { workspace = true }
bincode = { workspace = true }
bv = { workspace = true, features = ["serde"] }
curve25519-dalek = { workspace = true }
dlopen = { workspace = true }
dlopen_derive = { workspace = true }
fnv = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
xandeum-metrics = { workspace = true }
xandeum-rayon-threadlimit = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-vote-program = { workspace = true }

[target."cfg(target_os = \"linux\")".dependencies]
caps = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }

[lib]
name = "xandeum_perf"

[dev-dependencies]
matches = { workspace = true }
rand_chacha = "0.2.2"
xandeum-logger = { workspace = true }
test-case = { workspace = true }

[[bench]]
name = "sigverify"

[[bench]]
name = "discard"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
