[package]
name = "xandeum-zk-token-proof-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
bytemuck = { workspace = true, features = ["derive"] }
xandeum-program-runtime = { workspace = true }
xandeum-program-test = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-zk-token-sdk = { workspace = true }
