[package]
name = "xandeum-test-validator"
description = "Blockchain, Rebuilt for Scale"
readme = "../README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
xandeum-cli-output = { workspace = true }
xandeum-client = { workspace = true }
xandeum-core = { workspace = true }
xandeum-geyser-plugin-manager = { workspace = true }
xandeum-gossip = { workspace = true }
xandeum-ledger = { workspace = true }
xandeum-logger = { workspace = true }
xandeum-net-utils = { workspace = true }
xandeum-program-runtime = { workspace = true }
xandeum-program-test = { workspace = true }
xandeum-rpc = { workspace = true }
xandeum-rpc-client = { workspace = true }
xandeum-runtime = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-streamer = { workspace = true }
xandeum-tpu-client = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
