[package]
description = "Solana Program Test Framework"
name = "xandeum-program-test"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
chrono-humanize = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
xandeum-banks-client = { workspace = true }
xandeum-banks-interface = { workspace = true }
xandeum-banks-server = { workspace = true }
xandeum-bpf-loader-program = { workspace = true }
xandeum-logger = { workspace = true }
xandeum-program-runtime = { workspace = true }
xandeum-runtime = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-vote-program = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
xandeum-stake-program = { workspace = true }
