[package]
name = "xandeum-upload-perf"
description = "Metrics Upload Utility"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
serde_json = { workspace = true }
xandeum-metrics = { workspace = true }

[[bin]]
name = "xandeum-upload-perf"
path = "src/upload-perf.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
