[package]
name = "xandeum-send-transaction-service"
description = "Solana send transaction service"
documentation = "https://docs.rs/xandeum-send-transaction-service"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
log = { workspace = true }
xandeum-client = { workspace = true }
xandeum-measure = { workspace = true }
xandeum-metrics = { workspace = true }
xandeum-runtime = { workspace = true }
xandeum-sdk = { workspace = true }
xandeum-tpu-client = { workspace = true }

[dev-dependencies]
xandeum-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
