[package]
name = "xandeum-poh"
description = "Solana PoH"
documentation = "https://docs.rs/xandeum-poh"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
xandeum-entry = { workspace = true }
xandeum-ledger = { workspace = true }
xandeum-measure = { workspace = true }
xandeum-metrics = { workspace = true }
xandeum-runtime = { workspace = true }
xandeum-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
matches = { workspace = true }
rand = { workspace = true }
xandeum-logger = { workspace = true }
xandeum-perf = { workspace = true }

[lib]
crate-type = ["lib"]
name = "xandeum_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
