[package]
name = "xandeum-vote-program"
description = "Solana Vote program"
documentation = "https://docs.rs/xandeum-vote-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
xandeum-frozen-abi = { workspace = true }
xandeum-frozen-abi-macro = { workspace = true }
xandeum-metrics = { workspace = true }
xandeum-program = { workspace = true }
xandeum-program-runtime = { workspace = true }
xandeum-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
xandeum-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "xandeum_vote_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
